### ISSUE TITLE
Underline

### ISSUE THREAD

**Issue by Splike** [commonmark/commonmark-spec#591] opened 2019-06-25 09:21 UTC
Is it possible to add support for underline?

**Comment by vassudanagunta** [comment] 2019-06-25 19:17
Check out the [threads on underline in the CommonMark forum](https://talk.commonmark.org/search?q=underline). There is where the community discusses future extensions to CommonMark. 

But CommonMark v1's goal is to standardize/formalize existing Markdown. I think you should close this issue since it is not a bug in the current spec given the goals.

**Closed** 2019-06-25 19:52 UTC
